export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const FCM_UPDATE_REQUEST = 'FCM_UPDATE_REQUEST'
export const FCM_UPDATED = 'FCM_UPDATED'
